import React from 'react';
import PropTypes from 'prop-types';
import { Header, Jumbotron } from 'watson-react-components';

const demoName = 'Natural Language Understanding';
const DESCRIPTION = 'Natural Language Understanding is a collection of APIs that offer text analysis through natural language processing. This set of APIs can analyze text to help you understand its concepts, entities, keywords, sentiment, and more. Additionally, you can create a custom model for some APIs to get specific results that are tailored to your domain. This system is for demonstration purposes only and is not intended to process Personal Data. No Personal Data is to be entered into this system as it may not have the necessary controls in place to meet the requirements of the General Data Protection Regulation (EU) 2016/679.';

export default function Layout(props) {
  const { css, children } = props;
  return (
    <html lang="en">
      <head>
        <title>{demoName} Demo</title>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="og:title" content={demoName} />
        <meta name="og:description" content={DESCRIPTION} />
        <link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" href="/css/watson-react-components.min.css" />
        <link rel="stylesheet" href="/css/style.css" />
        <style date-aphrodite>
          {css.content}
        </style>
        <script type="text/javascript" src="scripts/bundle.js" defer async />
      </head>
      <body>
        <Header
          mainBreadcrumbs={demoName}
          mainBreadcrumbsUrl="https://www.ibm.com/watson/services/natural-language-understanding/"
          subBreadcrumbs="Demo"
          subBreadcrumbsUrl="https://natural-language-understanding-demo.ng.bluemix.net"
        />
        <Jumbotron
          serviceName={demoName}
          repository="https://github.com/watson-developer-cloud/natural-language-understanding-nodejs"
          documentation="https://console.bluemix.net/docs/services/natural-language-understanding/getting-started.html"
          apiReference="http://www.ibm.com/watson/developercloud/natural-language-understanding/api"
          version="GA"
          startInBluemix="https://console.bluemix.net/registration/?target=%2Fcatalog%2Fservices%2Fnatural-language-understanding%3FhideTours%3Dtrue%26cm_mmc%3D-_-Watson%2BCore_Watson%2BCore%2B-%2BPlatform-_-WW_WW-_-wdc-ref%26cm_mmc%3D-_-Watson%2BCore_Watson%2BCore%2B-%2BPlatform-_-WW_WW-_-wdc-ref%26cm_mmca1%3D000000OF%26cm_mmca2%3D10000409"
          description={DESCRIPTION}
        />
        <div id="root">
          {children}
        </div>
        <script type="text/javascript" src="scripts/bundle.js" />
        <script type="text/javascript" src="https://cdn.rawgit.com/watson-developer-cloud/watson-developer-cloud.github.io/master/analytics.js" />
      </body>
    </html>
  );
}

Layout.propTypes = {
  children: PropTypes.object.isRequired,
  css: PropTypes.object.isRequired, // attaching css generated by aphrodite
};
