import React from 'react';
import {Header, Jumbotron} from 'watson-react-components';

const demoName = 'Natural Language Understanding';
const DESCRIPTION = 'Natural Language Understanding is a collection of APIs that offer text analysis through natural language processing. This set of APIs can analyze text to help you understand its concepts, entities, keywords, sentiment, and more. Additionally, you can create a custom model for some APIs to get specific results that are tailored to your domain.';

export default function Layout(props) {
  return (
    <html>
      <head>
        <title>{demoName} Demo</title>
        <meta charSet="utf-8"/>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="og:title" content={demoName} />
        <meta name="og:description" content={DESCRIPTION} />
        <link rel="icon" href="/images/favicon.ico" type="image/x-icon"/>
        <link rel="stylesheet" href="/css/watson-react-components.min.css"/>
        <link rel="stylesheet" href="/css/style.css"/>
        <style date-aphrodite>{props.css.content}</style>
        <script type="text/javascript" src="scripts/bundle.js" defer async></script>
      </head>
      <body>
        <Header
          mainBreadcrumbs={demoName}
          mainBreadcrumbsUrl="http://www.ibm.com/watson/developercloud/natural-language-understanding.html"
          subBreadcrumbs="Demo"
          subBreadcrumbsUrl="https://natural-language-understanding-demo.mybluemix.net"
        />
        <Jumbotron
          serviceName={demoName}
          repository="https://github.com/watson-developer-cloud/natural-language-understanding-nodejs"
          documentation="http://www.ibm.com/watson/developercloud/doc/natural-language-understanding/"
          apiReference="http://www.ibm.com/watson/developercloud/natural-language-understanding/api"
          version="GA"
          startInBluemix="https://console.ng.bluemix.net/registration/?target=/catalog/services/natural-language-understanding/"
          description={DESCRIPTION}
        />
        <div id="root">
          {props.children}
        </div>
        <script type="text/javascript" src="/scripts/vendor/google-analytics.js" defer async></script>
      </body>
    </html>
  );
}

Layout.propTypes = {
  children: React.PropTypes.object.isRequired,
  css: React.PropTypes.object.isRequired,  // attaching css generated by aphrodite
};
